#pragma once

#include <QList>
#include <QMetaObject>
#include <memory>
#include <type_traits>

#include "Component/Component.h"
#include "Core_export.h"

namespace AppForge
{

class ComponentFactory;

// Base of the class every plugin declares with APPFORGE_PLUGIN. It builds the components registered in it with
// APPFORGE_REGISTER_COMPONENT: for each one ComponentFactory creates, it calls its build(<component>&), which
// instantiates the classes holding the logic of the component.
class CORE_EXPORT Plugin
{
  public:
    virtual ~Plugin();

    Plugin(const Plugin&) = delete;
    Plugin& operator=(const Plugin&) = delete;

    // Registers the component T in the plugin class P, which builds it with P::build(T&); see APPFORGE_REGISTER_COMPONENT.
    template <typename P, typename T> static bool add()
    {
        static_assert(std::is_base_of_v<Plugin, P>, "A component is registered in a class deriving from AppForge::Plugin");
        static_assert(std::is_base_of_v<Component, T>, "A component derives from AppForge::Component");
        // The check qobject_cast makes: without Q_OBJECT, T would be registered under the name of its base class.
        static_assert(QtPrivate::HasQ_OBJECT_Macro<T>::Value, "A component declares Q_OBJECT");
        static_assert(!std::is_final_v<T>, "A component cannot be final: Plugin derives from it");
        static_assert(!std::is_abstract_v<Instance<T>>, "A component implements every pure virtual function");
        static_assert(std::is_default_constructible_v<Instance<T>>, "A component needs a default constructor");
        static_assert(requires(P& plugin, T& component) { plugin.build(component); },
                      "The plugin class of a component declares a public build(<component>&)");
        registered<P>().append(ComponentType{.metaObject = &T::staticMetaObject, .builder = &build<P, T>});
        return true;
    }

    // Creates the plugin class P, with the components registered in it; see APPFORGE_PLUGIN.
    template <typename P> static std::unique_ptr<Plugin> instantiate()
    {
        static_assert(std::is_base_of_v<Plugin, P>, "A plugin class derives from AppForge::Plugin");
        static_assert(std::is_default_constructible_v<P>, "A plugin class needs a default constructor");
        std::unique_ptr<Plugin> plugin = std::make_unique<P>();
        plugin->m_componentTypes = registered<P>();
        return plugin;
    }

  protected:
    Plugin();

  private:
    friend class ComponentFactory;

    using Builder = std::unique_ptr<Component> (*)(Plugin& plugin);

    struct ComponentType
    {
        const QMetaObject* metaObject = nullptr;
        Builder builder = nullptr;
    };

    // The only instantiable class deriving from T, as it implements Component::builtByPlugin().
    template <typename T> class Instance final : public T
    {
        void builtByPlugin() override {}
    };

    template <typename P, typename T> static std::unique_ptr<Component> build(Plugin& plugin)
    {
        auto component = std::make_unique<Instance<T>>();
        static_cast<P&>(plugin).build(static_cast<T&>(*component));
        return component;
    }

    // The components registered in P while its plugin loads, before P is instantiated.
    template <typename P> static QList<ComponentType>& registered()
    {
        static QList<ComponentType> componentTypes;
        return componentTypes;
    }

    QList<ComponentType> m_componentTypes; // Read by ComponentFactory
};

namespace Generated
{

// Defined by APPFORGE_PLUGIN in each plugin, called by its root object generated by appforge_add_plugin.
std::unique_ptr<Plugin> createPlugin();

} // namespace Generated

} // namespace AppForge

// Declares Class as the plugin class of the plugin being built. Used once per plugin, in a source file:
// APPFORGE_PLUGIN(ExamplePlugin);
#define APPFORGE_PLUGIN(Class)                                                                                         \
    std::unique_ptr<AppForge::Plugin> AppForge::Generated::createPlugin()                                              \
    {                                                                                                                  \
        return AppForge::Plugin::instantiate<Class>();                                                                 \
    }                                                                                                                  \
    static_assert(true, "APPFORGE_PLUGIN ends with a semicolon")

// Registers Class, a component, in PluginClass, the plugin class (APPFORGE_PLUGIN) that builds it with
// PluginClass::build(Class&). Used once per component, in a source file: APPFORGE_REGISTER_COMPONENT(ExamplePlugin, Greeter);
// Registering can only throw when memory runs out, which ends the program while a plugin loads anyway.
// NOLINTBEGIN(bugprone-throwing-static-initialization)
#define APPFORGE_REGISTER_COMPONENT(PluginClass, Class)                                                                \
    [[maybe_unused]] static const bool APPFORGE_DETAIL_CONCAT(appforgeRegistered, __LINE__) =                          \
        AppForge::Plugin::add<PluginClass, Class>()
// NOLINTEND(bugprone-throwing-static-initialization)
#define APPFORGE_DETAIL_CONCAT(first, second) APPFORGE_DETAIL_CONCAT_IMPL(first, second)
#define APPFORGE_DETAIL_CONCAT_IMPL(first, second) first##second
